name: Deploy to EC2

on:
  push:
    branches: [main]  # or 'master' depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy index.html to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ec2_key.pem index.html ${{ secrets.EC2_HOST }}:/tmp/index.html
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_HOST }} << 'EOF'
            sudo mv /tmp/index.html /var/www/html/index.html
            sudo chown www-data:www-data /var/www/html/index.html
          EOF
